Repository mansi-saxena/Leetcode_solutions, pull requests merged in 2020-10, with the labels that each got.

#2 Update solution152
  solution152
Labels: hacktoberfest-accepted

#3 problem57
  problem57
Labels: hacktoberfest-accepted

#4 Added Solution to Problem 57
  problem57
Labels: hacktoberfest-accepted

#5 problem statement added.
  problem216
Labels: hacktoberfest-accepted

#6 Updated Solution 216
  problem216
Labels: hacktoberfest-accepted

#7 Problem statement added
  problem299
Labels: hacktoberfest-accepted

#8 Solution updated.
  problem299
Labels: hacktoberfest-accepted

#9 Problem Statement #165 added
  problem165
Labels: hacktoberfest-accepted

#10 Solution #165 added
  problem165
Labels: hacktoberfest-accepted

#11 Problem statement added
  problem290
Labels: hacktoberfest-accepted

#12 Solution 290 added
  problem290
Labels: hacktoberfest-accepted

#13 Problem #54 added
  problem54
Labels: hacktoberfest-accepted

#14 Added hactoberfest tag
  README.md
Labels: hacktoberfest-accepted

#15 Added #54 solution
  problem54
Labels: hacktoberfest-accepted

#16 Problem #118 added
  problem118
Labels: hacktoberfest-accepted

#17 Solution #118 added
  problem118
Labels: hacktoberfest-accepted

#18 Problem #459 added
  problem459
Labels: hacktoberfest-accepted

#19 Added #459 solution
  problem459
Labels: hacktoberfest-accepted

#20 Added problem statement
  problem835
Labels: hacktoberfest-accepted

#21 updated
  README.md
Labels: hacktoberfest-accepted

#22 solution 835 added
  problem835
Labels: hacktoberfest-accepted

#23 Added problem #498
  problem498
Labels: hacktoberfest-accepted

#25 Added #724 problem
  Problem724
Labels: hacktoberfest-accepted

#26 Updated the name and added #724 solution
  problem724
Labels: hacktoberfest-accepted

#24 added #498 solution
  problem498
Labels: good first issue, hacktoberfest-accepted

#27 Adde problem statement #470
  problem470
Labels: good first issue, hacktoberfest-accepted

#28 Update problem470
  problem470
Labels: documentation, good first issue, hacktoberfest-accepted

#29 Added #470 solution
  problem470
Labels: hacktoberfest-accepted

#30 added problem #969
  problem969
Labels: hacktoberfest-accepted

#31 Added #969 Solution
  problem969
Labels: hacktoberfest-accepted
